name: Continuous Integration
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Csharp code
      run: dotnet build

    - name: Build TypeScript code
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
        npm run build

    - name: Run Csharp tests
      run: dotnet test

    - name: Run TypeScript tests
      working-directory: ./DotnetTemplate.Web
      run: npm t

    - name: Run TypeScript Linter
      working-directory: ./DotnetTemplate.Web
      run: npm run lint